service: myserverlessproject
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser

plugins:
    - serverless-s3-sync

functions:
    getUser:
        handler: lambdas/endpoints/getUser.handler
        events:
            - http:
                  path: get-user/{ID}
                  method: GET
                  cors: true

resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: serverlessbucket10015

        MyDynamoDbTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: player-points
                AttributeDefinitions:
                    - AttributeName: ID
                      AttributeType: S
                KeySchema:
                    - AttributeName: ID
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST

custom:
    s3Sync:
        - bucketName: serverlessbucket10015
          localDir: UploadData